### ISSUE TITLE
Tab Name still as "eo4geo template"

### ISSUE THREAD

**Issue by simon-donike** [eo4geocourses/SpaSe_Urban-Heat-Islands#1]
<img width="371" alt="Bildschirmfoto 2020-08-10 um 12 36 08" src="https://user-images.githubusercontent.com/65158680/89774370-0b0e6180-db06-11ea-8c09-7cf104ae8419.png">

Wenn herausgefunden hast wie man es ändert, sag bitte kurz bescheid wie es geht. Danke

**Comment by VroniKr** [comment]
Im index.html gibts innerhalb des heads den tag <title>...</title>. Da kann mans ändern.
